module.exports = ERROR_CODE = {
	SOMETHING_WENT_WRONG: 100
}

module.exports = USER_ERROR_CODE = {
	EMAIL_ALREADY_REGISTERED: 301,
	PHONE_NUMBER_ALREADY_REGISTERED: 302,
	USER_NOT_SAVED: 303,
	USER_DATA_NOT_FOUND: 304,
	UPDATE_FAILED: 305
}